settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Investigating an Issue'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: bloor-co-uk # unique identifier
    name: Bloor.co.uk
    description: 'My website and email.' # default=empty
    url: 'https://bloor.co.uk/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: 4thAshby
    name: 4thAshby.org.uk
    description: '4th Ashby Scout Group Website.'
    url: 'https://4thashby.org.uk'
    method: GET
    expectStatus: 200

  - id: ACDS
    name: AshbyAndCoalvilleScouts.org.uk
    url: 'https://ashbyandcoalvillescouts.org.uk/'
    method: GET
    expectStatus: 200

  - id: Leics
    name: LeicestershireScouts.org.uk
    description: 'Leicestershire Scouts Website.'
    url: 'https://leicestershirescouts.org.uk'
    method: GET
    expectStatus: 200

  - id: willesley
    name: Willesley.org.uk
    description: 'Willesley Scout Campsite Website.'
    url: 'https://willesley.org.uk'
    method: GET
    expectStatus: 200

  - id: busyscouter
    name: busyscouter.com
    description: 'Busy Scouter Website.'
    url: 'https://busyscouter.com'
    method: GET
    expectStatus: 200

  - id: escouts
    name: Escouts.org.uk
    description: 'Escouts Discussion Board Website.'
    url: 'https://escouts.org.uk'
    method: GET
    expectStatus: 200

  - id: ticketing-tools
    name: TicketingTools.Online
    description: 'TicketingTools.Online'
    url: 'https://ticketingtools.online'
    method: GET
    expectStatus: 200

  - id: LME
    name: LandmarkExpertise.co.uk
    description: 'Landmark Expertise Website.'
    url: 'https://landmarkexpertise.co.uk'
    method: GET
    expectStatus: 200

  - id: Pathfinder
    name: PathfinderHost.Com
    description: 'Pathfinder Hosting Website.'
    url: 'https://pathfinderhost.com'
    method: GET
    expectStatus: 200

  - id: IntergrationHub
    name: IntegrationHub.CC
    description: 'Integration Hub.'
    url: 'https://integrationhub.cc'
    method: GET
    expectStatus: 200
